// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjMgr3XEFNt9cGyZe6bCPEMoGQOcR4kDI',
    appId: '1:27947559228:web:ca391cab37d4bcef911639',
    messagingSenderId: '27947559228',
    projectId: 'davidstore-757d8',
    authDomain: 'davidstore-757d8.firebaseapp.com',
    storageBucket: 'davidstore-757d8.firebasestorage.app',
    measurementId: 'G-KHGSFTPK9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACjuaBKzSJESZv3lUTz-L7hjd9swC5f9E',
    appId: '1:27947559228:android:f8897ae1458bfb39911639',
    messagingSenderId: '27947559228',
    projectId: 'davidstore-757d8',
    storageBucket: 'davidstore-757d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOVMYoZxKqi5AcM430hmd9XT0wE5UOxAQ',
    appId: '1:27947559228:ios:501f1427f4f7d47a911639',
    messagingSenderId: '27947559228',
    projectId: 'davidstore-757d8',
    storageBucket: 'davidstore-757d8.firebasestorage.app',
    androidClientId: '27947559228-7ilriij5gtkkb7pqvjdfl6bdc17hcm1f.apps.googleusercontent.com',
    iosClientId: '27947559228-1l6h6j2u0n8tp4ds9v0v66jjn0ql6hqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.davidstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOVMYoZxKqi5AcM430hmd9XT0wE5UOxAQ',
    appId: '1:27947559228:ios:501f1427f4f7d47a911639',
    messagingSenderId: '27947559228',
    projectId: 'davidstore-757d8',
    storageBucket: 'davidstore-757d8.firebasestorage.app',
    androidClientId: '27947559228-7ilriij5gtkkb7pqvjdfl6bdc17hcm1f.apps.googleusercontent.com',
    iosClientId: '27947559228-1l6h6j2u0n8tp4ds9v0v66jjn0ql6hqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.davidstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjMgr3XEFNt9cGyZe6bCPEMoGQOcR4kDI',
    appId: '1:27947559228:web:dee77f284bced67f911639',
    messagingSenderId: '27947559228',
    projectId: 'davidstore-757d8',
    authDomain: 'davidstore-757d8.firebaseapp.com',
    storageBucket: 'davidstore-757d8.firebasestorage.app',
    measurementId: 'G-B14C0ZFCST',
  );
}
